name: BuildPushSparkDockerImage

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        # Friendly description to be shown in the UI instead of 'version'
        description: "Enter valid tag"
        # Default value if no value is explicitly provided
        default: 3.1.2-jdk11
        # Input has to be provided for the workflow to run
        required: false

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - uses: actions/setup-java@v3.4.0
        with:
          java-version: '11'
      - uses: vemonet/setup-spark@v1
        with:
          spark-version: '3.1.2' # Exact version
          hadoop-version: '3.2'

      - name: Check Spark Version
        run: spark-submit --version

      - name: Get Previous tag
        id: previous_tag
        uses: WyriHaximus/github-action-get-previous-tag@master
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previous_tag.outputs.tag }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: 'Create new milestone'
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title: ${{ steps.semvers.outputs.patch }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: build docker images
        run: |
          $SPARK_HOME/bin/docker-image-tool.sh -r chethanuk -t 3.1.2-jdk11-${{ steps.previous_tag.outputs.tag }} -p $SPARK_HOME/kubernetes/dockerfiles/spark/bindings/python/Dockerfile -b java_image_tag=11-slim build
          $SPARK_HOME/bin/docker-image-tool.sh -r chethanuk -t 3.1.2-jdk11-${{ steps.previous_tag.outputs.tag }} -p $SPARK_HOME/kubernetes/dockerfiles/spark/bindings/python/Dockerfile push
